name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: queue-master
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK 1.8  
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 

    # Build
    - name: Build jar files
      run: ./gradlew build --build-cache -x test -x integrationTest

    # Unit test
    - name: Run unit tests
      run: ./gradlew test
    
    # Integration test
    - name: Integration Tests
      run: ./gradlew integrationTest

    #
    #
    # Upload coverage results to coveralls
    - name: Submit Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew -DrepoToken=${GITHUB_TOKEN} -DserviceJobId=${GITHUB_RUN_ID} -Dbranch=${GITHUB_REF} -DpullRequest=${GITHUB_HEAD_REF} -DserviceName=GITHUB jacocoTestReport coveralls
      
    # Push to Google Artifact Registry
    - name: Push to Google Artifact Registry
      env:
        IMAGE_NAME: queue-master
        PROJECT_ID: gd-gcp-gridu-devops-t1-t2
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - uses: webgtx/gcr-podman-action@v2
      env:
        IMAGE_NAME: queue-master
        PROJECT_ID: gd-gcp-gridu-devops-t1-t2
      with:
        project_id: ${{ env.PROJECT_ID }}
        image_id: ${{ env.IMAGE_NAME }}:latest
        host: europe-central2-docker.pkg.dev/kkanafotskyi
        auth_type: oauth2
        access_token: ${{ secrets.SERVICE_ACCOUNT_KEY }}

        